version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
image: Visual Studio 2017
configuration: Debug
platform: Any CPU
build_script:
- cmd: >-
    IF /I "%APPVEYOR_REPO_TAG%" EQU "TRUE" SET Configuration=Release

    MSBuild /BinaryLogger /Logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
on_success:
- ps: >-
    if($env:APPVEYOR_REPO_TAG_NAME -ne $null) {
      $pattern = "$env:APPVEYOR_REPO_TAG_NAME*.nupkg"
      Write-Host "Uploading artifacts that match $pattern"
      Get-ChildItem -Path "." -Recurse -Filter $pattern | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name -DeploymentName "NuGet Packages" }
    }
on_failure:
- ps: Get-ChildItem .\*.log -Recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
