'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System.Reflection
Imports System.Runtime.CompilerServices
Imports System.Runtime.InteropServices

' The below assembly information is auto-generated based on MSBuild properties.
' If you arrived at this file because of "error CS0579: Duplicate 'Assembly...' attribute", please
' remove the conflicting assembly attribute defined in the project item Properties\AssemblyInfo.vb

<Assembly: AssemblyCompany("$(AssemblyInfoCompany)")>
<Assembly: AssemblyConfiguration("$(AssemblyInfoConfiguration)")>
<Assembly: AssemblyCopyright("$(AssemblyInfoCopyright)")>
<Assembly: AssemblyCulture("$(AssemblyInfoCulture)")>
<Assembly: AssemblyProduct("$(AssemblyInfoProduct)")>
<Assembly: AssemblyTrademark("$(AssemblyInfoTrademark)")>
<Assembly: CLSCompliant($(AssemblyInfoCLSCompliant))>
<Assembly: ComVisible($(AssemblyInfoComVisible))>

