//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

/**************************************************************************************************

The below assembly information is auto-generated based on MSBuild properties.
If you arrived at this file because of "error CS0579: Duplicate 'Assembly...' attribute", please
remove the conflicting assembly attribute defined in the project item Properties\AssemblyInfo.cs

**************************************************************************************************/

[assembly: AssemblyCompany("$(AssemblyInfoCompany)")]
[assembly: AssemblyConfiguration("$(AssemblyInfoConfiguration)")]
[assembly: AssemblyCopyright("$(AssemblyInfoCopyright)")]
[assembly: AssemblyCulture("$(AssemblyInfoCulture)")]
[assembly: AssemblyFileVersion("$(AssemblyInfoFileVersion)")]
[assembly: AssemblyInformationalVersion("$(AssemblyInfoInformationalVersion)")]
[assembly: AssemblyProduct("$(AssemblyInfoProduct)")]
[assembly: AssemblyTrademark("$(AssemblyInfoTrademark)")]
[assembly: AssemblyVersion("$(AssemblyInfoAssemblyVersion)")]
[assembly: CLSCompliant($(AssemblyInfoCLSCompliant))]
[assembly: ComVisible($(AssemblyInfoComVisible))]
[assembly: TargetFrameworkAttribute("$(AssemblyInfoTargetFrameworkMoniker)", FrameworkDisplayName = "$(AssemblyInfoTargetFrameworkMonikerDisplayName)")]